### ISSUE TITLE
Dynamic search solver

### ISSUE THREAD

**Issue by lausilvag** [JuliaOpt/GLPK.jl#136]
Hi

I am new to Julia and I would like to know if there is any MIP optimization solver that performs dynamic search.

I have an optimization problem that exceeds 1000 variables allowed by student/research CPLEX license.

Cbc and GLPK solvers resolve MIP using Branch and Bound/Cut.

Is there any free solver that uses dynamic search?

thank you!
:)

**Comment by odow** [comment]
This question is better asked on Discourse forum: https://discourse.julialang.org/c/domain/opt/13

If you're looking for a high quality free MIP solver, your two options are really Cbc and GLPK.

I'm going to close this issue because it isn't related to a bug in GLPK.jl. Please post on Discourse if you have further questions.
