### ISSUE TITLE
glp_intopt: optimal basis to initial LP relaxation not provided

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/GLPK.jl#79]
This problem was working fine with GLPK last month (it was `GLPKOptimizerMIP` at the time) but with the recent updates, it now gives the following:
```julia
using JuMP
using GLPK
model = Model(with_optimizer(GLPK.Optimizer))
@variable(model, x, Int)
y = @variable(model)
@constraint(model, x <= 1)
@objective(model, Min, -5x + y)
JuMP.optimize!(model) # glp_intopt: optimal basis to initial LP relaxation not provided
JuMP.termination_status(model) # OtherError::TerminationStatusCode = 18
JuMP.primal_status(model) # UnknownResultStatus::ResultStatusCode = 8
```
This is causing failure in [StructJuMP tests](https://travis-ci.org/StructJuMP/StructJuMP.jl/jobs/430603900#L819-L822)

**Comment by odow** [comment]
Weird. That means that `model.intopt.presolve` must be turned on so that this branch is skipped.
https://github.com/JuliaOpt/GLPK.jl/blob/cb97aa8b04b4264058e018615ad2ad7b80086591/src/MOIWrapper.jl#L735-L743
Is this a change in the version of GLPK???

Here was the code from MPB
https://github.com/JuliaOpt/GLPKMathProgInterface.jl/blob/fdad2fb72a93be219573e48248b141380c821ee8/src/GLPKInterfaceMIP.jl#L460-L464

I'll dig into this tonight when I get time.

**Comment by blegat** [comment]
@odow Thanks for the fix ! Any objection against tagging v0.8.2 ?

**Comment by QINZHAOYU** [comment]
why does the glp_intopt() keep to output "Long-step dual simplex will be used"? Is there a way to turn it off?
Mine is  version 4.65.

**Comment by odow** [comment]
Try `with_optimizer(GLPK.Optimizer, msg_lev=GLPK.MSG_OFF)`.

p.s. In future, you should ask questions like this on https://discourse.julialang.org/c/domain/opt. More people read discourse, and you question might help other people in the future.
